---
# tasks file for config
#- name: packages | ensure apt list dir exists
#  file:
#    path: /var/lib/apt/lists/
#    state: directory
#    mode: 0755

#- name: Update&Upgrade
#  become: true
#  become_method: sudo
#  become_user: yc-sa-my-ansible-sa
#  ansible.builtin.apt:
#    name: aptitude
#    state: present
#    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - autoconf
      - dpkg-dev
      - file
      - g++
      - gcc
      - libc-dev
      - make
      - pkg-config
      - re2c
      - wget
    state: present
    update_cache: true
