#- name: Add Docker's official GPG key
#  ansible.builtin.shell:
#    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Set up the Docker stable repository
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable
    owner: root
    group: root
    mode: '0644'

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: true
