---
- name: Install Docker Engine
  hosts: app
  become: yes
  become_method: sudo
  roles:
    - role: docker

- name: Postgresql Install
  hosts: database
  become: yes
  become_method: sudo
  roles:
    - role: db
